language: java
sudo: false
jdk: oraclejdk8
install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "apkamatura"
        token:
          secure: ${SONAR_TOKEN}
        branches:
          - master
          - develop
          - feature/initialConfiguration

jobs:
  include:
    - name: unit
      script:
        - mvn test -P unit-testing sonar:sonar -B
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: integration
      if: branch in (master,develop)
      script:
        - mvn test -P integration-testing -B